export const CREATE_DB = 'CREATE_DB'
export const ADD_DB = 'ADD_DB'
export const REDUCE_DB = 'REDUCE_DB'
export const DELETE_DB = 'DELETE_DB'
export const UPDATE_CUR_SHOP_STATUS = 'UPDATE_CUR_SHOP_STATUS'
export const CHECK_DB = 'CHECK_DB'
export const UPDATE_LOCAL = 'UPDATE_LOCAL'
export const CLEAR_LOCAL = 'CLEAR_LOCAL'
